main/urls.py
from django.urls import path
from . import views

# Define a list of url patterns
urlpatterns = [
    path('', views.index, name="home"),
    #video routes
    path('upload/', views.upload_video, name='upload'),
    path('<int:video_id>/', views.view_video, name="view_video"),
    path('<int:video_id>/delete', views.delete_video, name='delete_video'),
    path('<int:video_id>/update', views.update_video, name='update_video'),
    path('search/', views.search_video, name='search_video'),

    path('video_list_api/', views.VideoListAPIView.as_view(), name='video_list_api'),
    path('view_video_api/<int:video_id>', views.ViewVideoAPIView.as_view(), name='view_video_api'),
    path('search_video_api/', views.SearchVideoAPIView.as_view(), name='search_video_api'),
    path('related_video_list_api/<int:video_id>', views.RelatedVideoListAPIView.as_view(), name='related_video_list_api'),

    path('update_video_api/<int:video_id>', views.UpdateVideoAPIView.as_view(), name='update_video_api'),
    path('delete_video_api/<int:video_id>', views.DeleteVideoAPIView.as_view(), name='delete_video_api'),
    path('post_comment_api/<int:video_id>', views.PostCommentAPIView.as_view(), name='post_comment_api'),
    path('upload_video_api', views.UploadVideoAPIView.as_view(), name='upload_video_api'),
    
]

tvstartup_exam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('home/', include("main.urls")),
    path('account/', include("account.urls")),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User

video_extensions = ["mp4", "mov", "avi", "wmv"]
thumb_extensions = ["png", "jpg", "jpeg"]

class Video(models.Model):
    title       = models.CharField(max_length=100)
    description = models.TextField()
    video_file  = models.FileField(upload_to="uploads/videos", 
                                validators = [FileExtensionValidator(allowed_extensions=video_extensions)])
    thumbnail   = models.FileField(upload_to="uploads/thumbnails", 
                                validators = [FileExtensionValidator(allowed_extensions=thumb_extensions)])
    date_posted = models.DateTimeField(default=timezone.now)
    uploader    = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ForeignKey('Video', on_delete=models.CASCADE)
    comment = models.TextField()
    created_on = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"User: {self.user} | {self.created_on.strftime('%b %d %Y %I:%M %p')}"

main/forms.py
from django import forms
from .models import Video

class VideoUploadForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title', 'description', 'video_file', 'thumbnail']

        widgets = {
            'title': forms.TextInput(attrs={
                'placeholder': 'Title',
                'autocomplete': 'title',
                'minlength': '1',
                'maxlength': '150',
                'class': 'textinput form-control',
                'required': 'required',
                'id': 'id_title',
            }),
            'description': forms.Textarea(attrs={
                'placeholder': 'Description',
                'autocomplete': 'description',
                'class': 'form-control',
                'rows': 5,
                'cols': 40,
                'required': 'required',
                'id': 'id_description',
            }),
            'video_file': forms.FileInput(attrs={
                'class': 'form-control-file',
                'accept': 'video/*',
            }),
            'thumbnail': forms.FileInput(attrs={
                'class': 'form-control-file',
                'accept': 'image/png, image/jpeg',
            }),
        }

    def is_valid(self) -> bool:
        return True

class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea(
        attrs = {
            "class": "form-control",
            "placeholder": "Leave a comment",
            "rows": 1   
        }
        ))

templates/layouts/delete_video.html
{% extends 'layouts/index.html' %}

{% block title %}Delete Video{% endblock title %}

{% block content %}
	<div class="container">
		<div class="row justify-content-center mt-5">
			<div class="col-md-6 col-sm-12 col-xs-12 text-center">
				<form method="POST">
					{% csrf_token %}
					<legend class="border-bottom mb-4">Delete Video</legend>
					<h5>Are You Sure?</h5>
					<p>This will delete the video forever.  This cannot be undone.</p>
					<button class="btn btn-outline-danger btn-block" type="submit">Delete</button>
				</form>
			</div>
		</div>
	</div>
{% endblock content %}

templates/layouts/edit_profile.html
{% extends 'layouts/index.html' %}

{% block title %}Edit Profile{% endblock title%}

{% block content %}
<div class="padding-navbar"></div>
<div class="container mb-5" id = "profile_container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-sm-12 col-xs-12">
            <div class="card text-dark ">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <legend class="border-bottom mb-4 pb-4">Update Profile</legend>
                    <div class="d-flex w-100 mt-0 pb-4 mb-4 border-bottom align-items-center">
                        <div>
                            <img class="rounded-circle" height="60px" width="60px" style="height:100px !important;" src="https://img.freepik.com/premium-vector/eyeglasses-bearded-asian-man-relaxed-standing-black-white-2d-vector-avatar-illustration-cheerful-mature-male-outline-cartoon-character-face-isolated-confident-headshot-posing-flat-portrait_151150-21790.jpg?w=740">
                        </div>
                        <div class="px-3 video-action">
                            <a class="video-icons icon-color mr-2 btn btn-rounded btn-outline-secondary" title="Delete Video" href="">
                                <ion-icon name="close-outline" class="mr-1 md hydrated" role="img"></ion-icon> Remove Photo
                            </a>
                        </div>
                    </div>
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    {{ form }}
                    <button class="btn btn-outline-primary btn-block mt-3" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/layouts/edit_video.html
{% extends 'layouts/index.html' %}

{% block title %}Update Video{% endblock title%}

{% block content %}
<div class="container mb-5">
    <div class="row justify-content-center">
        <div class="col-md-5 col-sm-12 col-xs-12">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <legend class="border-bottom mb-4">Update Video</legend>
                {{ form }}
                <button class="btn btn-outline-info btn-block mt-3" type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/layouts/home.html
{% extends 'layouts/index.html' %}

{% block title %}Home{% endblock title%}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            {% for video in videos %}
            <div class="card col-md-3 col-sm-12 mr-md-2 mt-5 p-3 border-0">
                <a href="{% url 'view_video' video.id %}"><img src="{{ video.thumbnail.url }}" width="256" height="144"/></a>
                <div class="card-body">
                    <a class="link-text" href="{% url 'view_video' video.id %}"><h5 class="text-center">{{ video.title }}</h5></a>
                    <p class="text-muted text-center m-0"> {{ video.uploader }}</p>
                    <p class="text-muted text-center"> {{ video.date_posted | date:"M d, Y" }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

templates/layouts/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://unpkg.com/@videojs/themes@1/dist/sea/index.css" rel="stylesheet">
    <link href="https://vjs.zencdn.net/7.8.3/video-js.css" rel="stylesheet" />

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
    <div class="padding-navbar"></div>
    {% include 'layouts/navigation.html' %}
    {% block content %}

    {% endblock content %}
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
    <script src="https://vjs.zencdn.net/7.8.3/video.js"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>

  {% block scripts %}
  {% endblock scripts %}
</html>

templates/layouts/navigation.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top">
    <a href="{% url 'home' %}" class="navbar-brand">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="navbar-search" method="GET" action="{% url 'search_video' %}">
            <input class="navbar-search-input" name="q" type="text" placeholder="Search" aria-label="Search" value={{ request.GET.q }}>
            <button type="submit" class="navbar-search-button"><ion-icon name="search-outline"></ion-icon></button>
        </form>
        <ul class="navbar-nav mr-auto"> 
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        MENU<span class="caret"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'upload' %}">Upload Video</a>
                    </div>
                </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="/media/uploads/profile_picture/eyeglass.jpg" width="35" height="35" class="d-inline-block rounded-circle" alt="Profile">
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'profile' %}">View Profile</a>
                        <a class="dropdown-item" href="{% url 'edit_profile' user %}">Edit Profile</a>
                        <a class="dropdown-item" href="{% url 'logout' %}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Sign Out</a>
                        <form id="logout-form" action="{% url 'logout' %}" method="POST" style="display: none;">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'login' %}" class="navbar-login">
                        <ion-icon name="person-circle-outline"></ion-icon>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/layouts/profile.html
{% extends 'layouts/index.html' %}

{% block title %}View Profile{% endblock title%}

{% block content %}
    
<div class="padding-navbar p-0"></div>
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-12">
            <div class="card align-items-center p-5 shadow" id = "profile_pic_container">
            <div class="d-flex w-100">
                <div class="pr-5">
                    <img class="rounded-circle" height="80px" width="80px" src="/media/uploads/profile_picture/eyeglass.jpg">
                </div>
                <div class="col pt-3">
                    <h4>{{ profile.first_name }} {{ profile.last_name }}</h4>
                    <p class="text-dark">@{{ profile.username }}</p>
                </div>  
                <div>
                    <form class="pt-2">
                        <a class="btn btn-outline-primary" href="{% url 'edit_profile' user %}">Edit Profile</a>
                    </form>
                </div>
            </div>
        </div>
        </div>
    </div>
    
	<div class="mt-5 mb-4 border-bottom"></div>

    <h3>Your Videos</h3>

    <div class="row justify-content-start mt-3 mb-5 no-gutters">
        {% for video in videos %}
            <div class="col-md-3">
                <div class="card mx-1 border-0 text-dark">
                    <img src="{{ video.thumbnail.url }}" class="card-img-top" alt="thumbnail">
                    <div class="card-body">
                        <h5 class="card-title text-left">{{ video.title }}</h5>
                        <p class="card-text text-muted text-left">
                            <span class="mr-4 d-none">{{ video.uploader }}</span>
                            <span>{{ video.date_posted | date:"M d, Y" }}</span>
                        </p>
                        <a href="{% url 'view_video' video.id %}" class="stretched-link"></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="padding-navbar"></div>
</div>
{% endblock %}

templates/layouts/search_videos.html
{% extends 'layouts/index.html' %}

{% block title %}Search Video{% endblock title%}

{% block content %}
    <h1>Search Videos</h1>
    <div class="container">
        <div class="row justify-content-center">
            {% for video in videos %}
            <div class="card col-md-3 col-sm-12 mr-md-2 mt-5 p-3 border-0">
                <a href="{% url 'view_video' video.id %}"><img src="{{ video.thumbnail.url }}" width="256" height="144"/></a>
                <div class="card-body">
                    <a class="link-text" href="{% url 'view_video' video.id %}"><h5 class="text-center">{{ video.title }}</h5></a>
                    <p class="text-muted text-center m-0"> {{ video.uploader }}</p>
                    <p class="text-muted text-center"> {{ video.date_posted | date:"M d, Y" }}</p>
                </div>
            </div>
            {% endfor %}
{% endblock content %}

templates/layouts/upload_video.html
{% extends 'layouts/index.html' %}

{% block title %}Upload Video{% endblock title%}

{% block content %}
<div class="container mb-5">
    <div class="row justify-content-center">
        <div class="col-md-5 col-sm-12 col-xs-12">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <legend class="border-bottom mb-4">Upload Video</legend>
                <div id="drop-area" class="drop-area">
                  <div>Drag and drop your videos here</div>
                    <div>or</div>
                    <div>
                        <input type="file" id="id_video_file" multiple accept="video/*" name="video_file" style="display:none">
                        <label class="btn btn-outline-info mt-3" for="id_video_file" id="fileSelect">Click here to select files</label>
                    </div>
                </div>
                <div id="file-list">
                  <p>No videos uploaded yet</p>
                </div>
                <button class="btn btn-outline-info mt-3" id="continueBtn" style="display: none;">Continue</button>
                <div id="videoDetails" style="display: none;">
                    <h3>Video Details</h3>
                    <div id="videoForms"></div>
                </div>
                <button id="submit-button" style="display: none;" class="btn btn-outline-info btn-block mt-3" type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/layouts/view_video.html
{% extends 'layouts/index.html' %}

{% block title %} {{ video.title }} {% endblock title%}

<input type="hidden" id="play-video-url" data-url="{% url 'view_video' video.id %}" />

{% block content %}
	<div class="container" id="video-details">
		<div class="row mt-5 video-player" data-setup='{"playbackRates": [0.5, 1, 1.5, 2], "fluid": true}'>
			<div class="col-md-2"></div>
			<div class="col-md-8">
					<video-js
					width="720"
					height="205"
					controls
					data-setup='{"playbackRates": [0.5, 1, 1.5, 2], "fluid": true}'>
					<source src="/media/{{ video.video_file }}" type="video/mp4">
					<p class="vjs-no-js">
					To view this video please enable Javascript, and consider upgrading to a web browser that <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
					</p>
					</video-js>
			</div>
		</div>
		<div class="row align-contents-center">
			<div class="col-md-2"></div>
			<div class="col-md-8 col-sm-12 col-xs-12">
				
				<div class="d-flex pt-4 w-100">
					<div class="col pl-0">
						<h5>{{ video.title }}</h5>
						<div class="text-muted">
							<p>{{ video.date_posted | date:"M d, Y" }}</p>
						</div>
					</div>
					<div class="video-action px-3">
						<button title="Share" class="btn btn-rounded btn-outline-secondary" type="button"  data-toggle="modal" data-target="#exampleModal">
							<ion-icon class="mr-1" name="share-social-outline" >
		                    </ion-icon> Share
						</button>
	                    
	                    <!-- Modal -->
	                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	                        <div class="modal-dialog" role="document">
	                        <div class="modal-content">
	                            <div class="modal-header">
	                            <h5 class="modal-title" id="exampleModalLabel">Share This Video!</h5>
	                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	                                <span aria-hidden="true">&times;</span>
	                            </button>
	                            </div>
	                            <div class="modal-body text-center">
	                                <ion-icon class="social-share-icons twitter-social-color" name="logo-twitter" data-sharer="twitter" data-title="Checkout {{ object.title }}!" data-hashtags="" data-url="http://localhost:8000/videos/{{ object.pk }}">Share on Twitter</ion-icon>                                
	                                <ion-icon class="social-share-icons facebook-social-color" name="logo-facebook" data-sharer="facebook" data-title="Checkout {{ object.title }} by {{ object.uploader }}!" data-hashtags="" data-url="http://localhost:8000/videos/{{ object.pk }}">Share on Facebook</ion-icon>
	                                <ion-icon class="social-share-icons reddit-social-color" name="logo-reddit" data-sharer="reddit" data-title="Checkout {{ object.title }} by {{ object.uploader }}!" data-hashtags="" data-url="http://localhost:8000/videos/{{ object.pk }}">Share on Reddit</ion-icon>
	                                <p class="mt-3">Link: http://localhost:8000/videos/{{ object.pk }}</p>
	                            </div>
	                        </div>
	                        </div>
	                    </div>
					</div>
				</div>
				
				{% if video.uploader == user %}
					<div class="video-action">
						<a class="video-icons icon-color mr-2 btn btn-rounded btn-outline-secondary" title="Edit Video" href="{% url 'update_video' video.id %}">
						    <ion-icon name="pencil-outline" class="mr-1"></ion-icon> Edit video
						</a>
						<a class="video-icons icon-color mr-2 btn btn-rounded btn-outline-secondary" title="Delete Video" href="{% url 'delete_video' video.id %}">
                            <ion-icon name="close-outline"  class="mr-1"></ion-icon> Delete video
                        </a>
					</div>
				{% endif %}
				<div class="card mt-3 text-dark b-0">
					<div class="card-body mt-0">
						<div class="p-4">
							{% if user.is_authenticated %}
                                <form id="comment-form" method="POST">
                                    {% csrf_token %}
                                    <legend class="border-bottom d-none mb-4">Leave a Comment!</legend>
                                    {{ form }}
                                    <input type="submit" class="btn btn-primary btn-block" value="Post comment"/>
                                </form>
						    {% else %}
						        <a class="btn btn-primary btn-block" href="{% url 'login' %}">Sign In To Post a Comment!</a>
						    {% endif %}
						</div>
					</div>
				</div> 
				<div id="comment-section" class="mt-4">
					<div class="pb-2">Comments</div>
					{% for comment in comments %}
					<div class="d-flex w-100 mt-0 py-3 border-top">
						<div>
							<img class="rounded-circle" height="40px" width="40px" src="https://img.freepik.com/premium-vector/eyeglasses-bearded-asian-man-relaxed-standing-black-white-2d-vector-avatar-illustration-cheerful-mature-male-outline-cartoon-character-face-isolated-confident-headshot-posing-flat-portrait_151150-21790.jpg?w=740">
						</div>
						<div class="col ">
							<p class="mb-1"><strong>@{{ comment.user }}</strong></p>
							<p class="mb-1">{{ comment.comment }}</p>
						</div>
					</div>
					{% endfor %}
				</div>
	</div>
</div>
<div class="padding-navbar"></div>

{% endblock content %}

{% block scripts %}
<script type="text/javascript">
	$(document).ready(function() {
		$(document).on('submit', '#comment-form', function(e) {
			e.preventDefault();

			console.log('entering ajax')

			$.ajax({
				type:'POST',
				url:$('#play-video-url').attr("data-url"),
				data:{
					comment:$('#id_comment').val(),
					csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
				},
				success: function (data){

					console.log(data)
					console.log(data.user)
					console.log(data.comment)
					console.log(data.commentuser)
					
					var newDiv = document.createElement('div');

					var commentHTML = `
						<div class="row mt-3">
							<div class="col-md-8 col-sm-12 border-bottom">
								<h5>${data.user}</h5>
								<p>${data.comment}</p>
							</div>
						</div>
					`;

					// Set the content and style of the new div
					newDiv.innerHTML = commentHTML;
				
					// Get the parent element of the comments section
					var commentsSection = document.getElementById('comment-section');
				
					// Insert the new div before the comments section
					commentsSection.parentNode.insertAfter(newDiv, commentsSection);
					console.log('finished adding new comment')
				}
			});
			
			var textbox = document.getElementById('id_comment');
            textbox.value = '';
		});
	});
</script>
{% endblock scripts %}